- src/BootKeyboard/BootKeyboard.h
- src/MultiReport/Keyboard.h
To avoid a compiler warning (with `-Woverloaded-virtual`), mark `Print::write` as private in both `BootKeyboard.h` and `MultiReport/Keyboard.h`.
The original `Print::write` is not used anywhere, the intent is clearly to hide it. Let the compiler know that, too.
> Make the hiding of Print::write explicit

- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
In case one would like to implement behaviour that changes when a modifier is active, one would need to know the state of the modifier. While it is possible to track this on a higher level, this is something already available in the report. As such, the most straightforward way to achieve this goal is to have a function that looks into the report.
This patch does just that.
> Add a method to return if a modifier is active

- src/BootKeyboard/BootKeyboard.h
- src/MultiReport/AbsoluteMouse.h
- src/MultiReport/ConsumerControl.h
- src/MultiReport/Gamepad.h
- src/MultiReport/Keyboard.h
- src/MultiReport/Mouse.h
- src/MultiReport/SystemControl.h
Flexible arrays is not a C++ feature. It appears that in GCC 4.x they are allowed, but when compiling this code with GCC 6.x a flexible array declaration will produce an error.
I have not delved deeply into this code, but it appears to me that the whole8, whole16 and whole32 members inside the unions are meant to provide an "alternate" view into the unions, that are just arrays. But since these are never used it should be safe to remove them.
I may be completely wrong about all this. If so, just ignore my pull request.
> Remove all 'flexible arrays', which is not a valid C++ construct

- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
Add a LEDS usage page to the HID descriptors, and a `.getLEDs` method pass-through.
Depends on keyboardio/Arduino-HID#1.
> Implement Keyboard.getLEDs()

- src/MultiReport/ConsumerControl.cpp
- src/MultiReport/ConsumerControl.h
Instead of always sending a report on every `press`, `release`, and `releaseAll`, let the user of this code decide when to send the report. This will allow us to treat `ConsumerControl` the same way we do with `Keyboard`, and clear the report each cycle. That in turn will help us not send many presses for the same key in a single report.
This is one half of the change that is needed to address keyboardio/Kaleidoscope#176.
> ConsumerControl: Report separately from press / release

- src/DeviceAPIs/AbsoluteMouseAPI.h
- src/DeviceAPIs/AbsoluteMouseAPI.hpp
- src/MultiReport/AbsoluteMouse.cpp
We do not use the wheels on `AbsoluteMouse`, and having the horizontal wheel added to the descriptor causes issues at least on Linux, rendering the whole of `AbsoluteMouse` unusable. With the horizontal wheel support gone, it works again.
Fixes #15.
> AbsMouse: Remove support for the horizontal scroll wheel

- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
I'm working on a plugin that needs to be able to send a modified copy of the previous HID report during the scan (`eventHandlerHooks`). In the middle of the scan, the new report is incomplete, so if I call `sendKeyboardReport()`, I'll likely leave out some keycodes occasionally, resulting in spurious keypresses (the extra report doesn't add `X` because it gets sent when the scan is only at `A`, for instance – then the normal report adds it, and we could get an extra `X` that shouldn't happen).
By far the simplest way to enable this feature is to provide a function that copies the previous report to the current one. This is not without pitfalls, of course: I think this might introduce some timing issues where keys that toggle on or off synchronously with other events could result in …
> Function to copy the last keyboard report

- src/DescriptorPrimitives.h
- src/MultiReport/Mouse.cpp
Instead of bundling X, Y, and Wheel together, pull out the latter, split it into resolution modifier + wheel, and base the horizontal wheel on top of that. Functionally, this should be the same, just structured in a different way.
This seems to upset at least Linux a lot less, and will hopefully fix #18.
> Mouse: Rework the USB descriptors

- src/MultiReport/Mouse.cpp
- src/MultiReport/Mouse.h
Instead of sending a report immediately after a move or a button press, let the user of the library decide when to send it. While there, also expose a `releaseAll` method, so we follow the same pattern as `Keyboard`, allowing the user to send & clear the report each cycle.
This separation is required to address keyboardio/Kaleidoscope-MouseKeys#10.
> Mouse: Pull sendReport out of move & buttons

- src/MultiReport/Mouse.cpp
As it turns out, the *real* problem was two typos, `D_USAGE_MINIMUM` and `D_USAGE_MAXIMUM` were used in the horizontal wheel descriptor instead of `D_LOGICAL_MINIMUM` and `D_LOGICAL_MAXIMUM`.
This patch reverts the previous USB HID descriptor rework, and fixes the horizontal wheel descriptor only, saving us some 46 bytes of program space.
Tested & works on Linux, but to make sure we don't re-break OSX, testing there would be most appreciated.
> Revert the Mouse USB HID descriptor change, and fix hWheel better

- src/MultiReport/Mouse.cpp
Because `Mouse` is *always* instantiated, the constructor always runs, and thus, the node is always registered whenever the `Mouse` object is referenced, even if done so in code that gets optimized out. To combat this, and allow the compiler to optimize out `Mouse` fully, do the append in `Mouse.begin`. This way, if the `Mouse` global is referenced by code that gets optimized out, the constructor will be optimized out, allowing the full object to get dropped. As we call `Mouse.begin` during `setup`, there is no risk doing a late append, either.
This addresses the most important part of keyboardio/Kaleidoscope#257.
> Mouse: Append the descriptor late, in Mouse.begin

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
This does a couple of things:
- Guards `sendReport` the way it is guarded elsewhere too.
- Adds `isModifierActive` and `wasModifierActive`.
- Remove the (unused) consumer reports from the HID descriptor.
- Add a way to set a default protocol (USB spec says we should default to report, which is what BootKeyboard did, but some situations prefer defaulting to boot - this allows us to do that).
- Add a way to forcibly set the protocol.
These are changes lifted out of #20, without the fallback parts, as that will be implemented elsewhere.
> Various BootKeyboard updates

- src/MultiReport/Mouse.cpp
Without a report count, the HID descriptor is invalid, and while Linux and Windows appear to handle that gracefully, OSX does not, and disables the entire device.
Fixes #25.
Untested, but I have a good feeling about this. If anyone with OSX handy could test if this works, that would be lovely.
> Mouse: Add a missing REPORT_COUNT to the horizontal wheel Usage

- src/MultiReport/Keyboard.cpp
In Kaleidoscope/src/kaleidoscope/hid.cpp, there is a description of a ChromeOS bug that causes certain modifier keys to be missed if they are added in the same Keyboard HID report as a printable keycode (e.g. `shift`+`[`). The workaround there sends an extra report any time `hid::pressKey()` is called with a `Key` that has a modifier flag bit set. That solves the problem in one case, but there are other ways for a report to get sent with both a new modifier and a new normal keycode. There is also the possibility that a plugin might want to stop that report from being sent, and there's also the problem that calling `pressKey()` for a modified key when the report is only partially complete could cause unintentional key release events.
This change is a general fix for the problem, regardless …
> Improved workaround for ChromeOS modifier bug

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
MacOS needs the HID descriptors and the report to have a particular layout. Namely, the descriptors need to have LEDs first, one padding byte, 6KRO keys, and modifiers last. The report must have modifiers first, padding, then the keys.
> Fix up BootKeyboard to work under OSX

- src/BootKeyboard/BootKeyboard.cpp
> BootKeyboard: Use the HID descriptor macros

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
The primary reason for this change is to allow us to get rid of WakeupKeyboard in HostPowerManagement, because having two boot-keyboard enabled endpoints has the chance of confusing the hell out of certain operating systems, bootloaders, or BIOSes. As in, whichever gets found first, wins, which becomes a problem when WakeupKeyboard wins: that one does not implement a real keyboard. If it wins, one will be able to wake up a sleeping systems, but will be unable to type. That is not behaviour we desire.
If we drop WakeupKeyboard, we need another way to have a boot-proto-enabled keyboard that defaults to boot proto, which is what this patch does with BootKeyboard.
The reason we need to default to BOOT, contrary to what the USB spec says, is because Linux, Windows and OSX will only enable …
> BootKeyboard: default to BOOT protocol

- src/BootKeyboard/BootKeyboard.cpp
When releasing a modifier, we were computing the bit index wrong: we substracted `HID_KEYBOARD_LAST_MODIFIER` from the keycode (going into negatives and wrapping around) instead of `HID_KEYBOARD_FIRST_MODIFIER`. Computing the index wrong meant that `BootKeyboard.release(Key_LeftShift.keyCode)` never cleared the shift bit from `_keyReport.modifiers`. This had undesired effects when BootKeyboard was active, and we explicitly wanted to release a single key, but keep the rest of the report intact.
> BootKeyboard: Fix modifier release

- src/BootKeyboard/BootKeyboard.cpp
Because OSX behaves strangely when HID_SET_IDLE is implemented (symptoms include key chatter), we disable it for now. Other operating systems to not suffer if we force the idle setting to zero, either.
> BootKeyboard: Disable HID_SET_IDLE

- src/BootKeyboard/BootKeyboard.cpp
Instead of plugging the BootKeyboard at constructor-time, do so at begin()-time, so we can control when it happens. We want to control when it happens so that we can set the default protocol based on various boot-time considerations, without having to recompile the firmware.
> BootKeyboard: Move the plugging to .begin()

- src/MultiReport/Mouse.cpp
- src/MultiReport/Mouse.h
This mirrors `move()`, and the intent is to use it when releasing a mouse key outside of the main event loop (such as during a macro).
> Mouse: Implement Mouse_::stop()

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
Part of the resolution for [532 on Kaleidoscope](https://github.com/keyboardio/Kaleidoscope/issues/532).
> Add functions for determining whether any modifiers are/were active

- src/BootKeyboard/BootKeyboard.cpp
- src/HID.cpp
- src/HID.h
- src/HIDReportObserver.cpp
- src/HIDReportObserver.h
- src/SingleReport/SingleAbsoluteMouse.cpp
The new observer class is used in all places where reports are
send. It replaces the old observer that was solely used by HID.*.
Signed-off-by: Florian Fleissner <florian.fleissner@inpartik.de>
> Added a HIDReportObserver class

- src/HID-Settings.h
- src/HID.cpp
- src/MultiReport/SystemControl.cpp
- src/arch/avr.cpp
- src/arch/samd.cpp
Turns out that my previous attempts at a SAMD port weren't enough, and there are a number of things left to fix up. This patchset "fixes" the host wakeup code (previously it compiled, but failed to link), and updates a few places that need special handling on SAMD.
The host wakeup code compiles and links, but doesn't work yet. I left the attempt in regardless, because it's a pointer to where we should look when debugging it further.
Tested the updates on both AVR and SAMD, and everything appears to function correctly, apart from the wakeup on SAMD.
> Finalised SAMD port

- src/HID.cpp
Marking the method weak allows us to override it elsewhere, which in turn makes it possible to have a different shortname than 'kbio01'.
This is the first half of the fix for #54.
> HID: Mark HID_::getShortName weak

- src/MultiReport/ConsumerControl.cpp
- src/MultiReport/Keyboard.cpp
- src/MultiReport/SystemControl.cpp
To be able to better control when and in which order HID descriptors are appended, delay doing so until calling `.begin()`, at least for NKRO-keyboard and Consumer- and SystemControl. The Mouse class was already doing the same.
This is a pre-requisite for #59.
> Delay appending the HID descriptors until .begin()

- src/MultiReport/ConsumerControl.cpp
- src/MultiReport/Keyboard.cpp
- src/MultiReport/SystemControl.cpp
Reverts keyboardio/KeyboardioHID#62, because it causes issues on the Dygma Raise. With this applied, the keyboard either doesn't register:
```
[  +0.110901] usb 2-3.4.2: New USB device found, idVendor=1209, idProduct=2201, bcdDevice= 1.00                                                    
[  +0.000006] usb 2-3.4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3                                                                
[  +0.000003] usb 2-3.4.2: Product: Dygma                                                                                                          
[  +0.000003] usb 2-3.4.2: Manufacturer: Raise                                                                                                     
[  +0.000002] usb 2-3.4.2: SerialNumber: …
```
> Revert "Delay appending the HID descriptors until .begin()"

- .astylerc
- Makefile
- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/DescriptorPrimitives.h
- src/DeviceAPIs/AbsoluteMouseAPI.h
- src/DeviceAPIs/AbsoluteMouseAPI.hpp
- src/HID.cpp
- src/HID.h
- src/HIDReportObserver.h
- src/HIDTables.h
- src/LEDs.h
- src/MouseButtons.h
- src/MultiReport/AbsoluteMouse.cpp
- src/MultiReport/AbsoluteMouse.h
- src/MultiReport/ConsumerControl.cpp
- src/MultiReport/ConsumerControl.h
- src/MultiReport/Gamepad.cpp
- src/MultiReport/Gamepad.h
- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
- src/MultiReport/Mouse.cpp
- src/MultiReport/Mouse.h
- src/MultiReport/SystemControl.cpp
- src/MultiReport/SystemControl.h
- src/SingleReport/SingleAbsoluteMouse.cpp
- src/SingleReport/SingleAbsoluteMouse.h
- src/arch/samd.cpp
This updates the code in KeyboardioHID to (roughly) use the coding style of Kaleidoscope. In a few places, I didn't bother, and in some cases, it wasn't possible (because of the interface with Arduino code).
Notably, I changed the `make astyle` target to call astyle with the same options used in Kaleidoscope, via a `.astylerc` file and the `--project` option. Other than that, there should be no code changes other than refactoring variable names.
> Conform to Kaleidoscope C++ coding style

- src/MultiReport/Keyboard.h
These were originally made public at my request in order to (imperfectly) work around a mid-cycle report problem in Qukeys.  That problem was that, if a plugin wanted to send one or more extra reports in response to a keyswitch toggling on or off, it was not possible to safely send such a report from an `onKeyswitchEvent()` handler, because the new report was likely incomplete.  The workaround was to give plugins direct access to the old report's data structure, which could then be modified and sent. This wasn't a good solution, however, because of potentially complex plugin interactions.
That workaround has since been replaced with a system that only sends reports in another handler function (`beforeReportingState()` or `afterEachCycle()`).  This works, and while it creates more …
> Make Keyboard HID report data variables private

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
Instead of doing the plugging late, in `.begin()`, allow setting the protocol in the constructor, and mark the global object weak, so it can be overridden in a user sketch, with one that has the desired protocol set.
We originally moved the `PluggableUSB().plug(this)` call from the constructor to `.begin()` in 186c8b4538ee3fb8d014c7871ba12a1412b8c1dd, to make it possible to set the default protocol the boot keyboard boots up with. However, this never really worked reliably, and was a bit finicky.
By allowing to override the object, we can set the protocol more reliably.
As a side effect, by moving the plugging to the constructor, the library will also work better with the (currently work in progress) arduino core for GD32 - though that needs other changes on top of this.
> BootKeyboard: Reorganize how the default protocol can be set

- src/BootKeyboard/BootKeyboard.cpp
The constructor for `BootKeyboard` had its member initialization list arguments (`protocol` and `default_protocol`) in the wrong order; they're required to be in the same order the member variables are declared in the class definition in the header file.  This was causing `-Wreorder` warnings, caused by #73.
The fix was very simple, and since it doesn't affect the parameters of the constructor, only the member initialization list, it's a very minimal change.
> Fix init order warning for BootKeyboard constructor

- src/MultiReport/Mouse.cpp
- src/MultiReport/Mouse.h
Two changes: a simplification and correction of the suppression of no-op mouse reports, and a correction of the `click()` method.
The logic for no-op report suppression had been incorrect, so we would sometimes send a report with the button state unchanged and all zeros for cursor and scroll movement.  This fixes that, and also makes the code clearer and streamlines things (there's no point in storing a full copy of the previous mouse report when the only thing that it's valid to compare against is the button state).
The `click()` method was built assuming that a report would be sent every cycle, so it didn't bother sending the second ("release") report explicitly.  This is not a safe assumption (current Kaleidoscope doesn't do this).  Also, if the button(s) in question were already held, …
> Simplify and correct Mouse features

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/HID.cpp
- src/HID.h
buffers that are modulo 16 bits in size.
This is currently necessary because these fields are read
directly from the USB peripheral with ‘usbd_ep_data_read’,
which can only read in 16-bit chunks (as of version 2.1.2
of the firmware library).
> Create unions for fields we receive from the host with backing buffers that are modulo 16 bits in size.

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/HID.cpp
- src/HID.h
This is an alternative to #83, with the code changes confined to the method implementations in the affected source files.  It has the benefit of not affecting the virtual HID code in Kaleidoscope, and I think it's much easier to follow than the `union` approach.
> Alternative workaround for the GD32 `void*` -> `uint16_t*` cast problem

- src/BootKeyboard/BootKeyboard.cpp
- src/DeviceAPIs/AbsoluteMouseAPI.hpp
- src/MultiReport/ConsumerControl.cpp
- src/MultiReport/Gamepad.cpp
- src/MultiReport/Keyboard.cpp
- src/MultiReport/Mouse.cpp
- src/MultiReport/SystemControl.cpp
We inherited code from Nico Hood's HID project that would always send a
"release" report at init time.  This is...not actually correct on a
normal device. This commit reverts that behavior, which, among other
things, caused the Keyboardio Model 100 to freeze on boot on Intel macs.
Tested on the Model 01 and the Model 100
That code came with this comment:
// Force API to send a clean report.
// This is important for and HID bridge where the receiver stays on,
// while the sender is resetted.
Added in this commit:
commit eff788e5405f47ce348c2f7cee2c47aab95c9efd
Author: NicoHood <NicoHood@users.noreply.github.com>
Date:   Sun Oct 25 14:26:55 2015 +0100
Made Keyboard API a lot more flexible
> Don't send empty reports upon enumeration.

- src/MultiReport/SystemControl.cpp
Since ab9702352f09f4f4ceee0ba639f872d00df06e93,  `SystemControl_::begin()` is a no-op, calling it in `release()` and `releaseAll()` is not doing what it did prior to that commit: call `end()`, which is what the release functions really wanted to do in the first place.
Lets do the right thing then, and call `end()`.
> SystemControl: Call the right function in release() and releaseAll()

- src/MultiReport/Keyboard.cpp
- src/MultiReport/Keyboard.h
There was a fencepost error in counting the number of bits in the key bitmap. This resulted in the report descriptor declaring one more Usage than items in the report, which might cause validation problems on some HID implementations.
The only affected Usage was Keypad Hexadecimal, which is probably not used often.
> fix NKRO report fencepost

- src/BootKeyboard/BootKeyboard.cpp
- src/HID.cpp
Always respond with the current Idle period, possibly set by the host. Also, set the initial idle period to 0 (indefinite), because that's how we actually behave.
> fix get/set idle

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/HID-Settings.h
- src/HID.cpp
- src/SingleReport/SingleAbsoluteMouse.cpp
Only reset boot/report protocol on USB bus reset. Windows 10 will sometimes try to cache report descriptors if it has high confidence that it's a device it's seen before. This means it won't retrieve either the configuration descriptor set or the report descriptors when resetting after receving control from the BIOS/UEFI. The BIOS or UEFI probably set the boot keyboard to boot protocol, which meant that when Windows regained control, the boot keyboard was still in boot protocol, contrary to the USB HID specification.
This requires the higher-level driver to call a polling function, because detection of USB reset events isn't as portable as checking the USB device configuration.
> reset protocol on bus reset

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
- src/HID.cpp
- src/SingleReport/SingleAbsoluteMouse.cpp
Use a singleton for BootKeyboard to make sure that it is the first HID interface. Some UEFIs or BIOSes appear to only recognize a boot keyboard if it's the first HID interface.
> make BootKeyboard first HID

- src/BootKeyboard/BootKeyboard.cpp
- src/BootKeyboard/BootKeyboard.h
Instead of having a poll function to check for USB reset in BootKeyboard, use an onReset hook instead.
This should also fix the simulator build failures, which were due to a lack of mocking of `USBDevice` in the virtual hardware.
> use an action hook onReset for BootKeyboard

- src/BootKeyboard/BootKeyboard.cpp
- src/HID.cpp
Remove the GD32 `recvControl` workaround, because changes to the USB core mean that it's no longer required.
> remove GD32 `recvControl` workaround

- src/MultiReport/AbsoluteMouse.cpp
- src/MultiReport/Mouse.cpp
- src/SingleReport/SingleAbsoluteMouse.cpp
It's possible that some KVM switches or OSes didn't like the mouse devices, because the axes aren't wrapped in a Pointer Physical Collection.
Also use the correct macro for the item tag for the multibyte AC Pan on the relative mouse. No change in encoding; it's just a more meaningful macro.
> use pointer collection in mouse descriptors
